apiVersion: v1
kind: Service
metadata:
  name: version-bump
  labels:
    app: version-bump
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: version-bump
      protocol: TCP
  selector:
    app: version-bump
