name: Run Build and Push Image
on:
  push:
    branches:
      - main
jobs:
  build-push-image:
    name: Build-Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docker HUB Login
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get tag for image
      - name: Get tag for image and chart
        run: |-
          echo "IMAGE_TAG=$(cat ./setup.py | grep "version=" | head -n 1 | sed 's/[^0-9.]*//g')" >> $GITHUB_ENV

      # Build docker image
      - name: Build Docker Image
        run: |-
          docker build --tag javid907/bump-version-bot:${{ env.IMAGE_TAG }} . --file Dockerfile

      # Push image to Docker Global repo
      - name: Push Dccker Image to GCR
        run: |-
          docker push javid907/bump-version-bot:${{ env.IMAGE_TAG }}

      # Lint Chart Helm
      - name: Linting Helm Chart
        run: helm lint ./chart/
